- name: software | install basic packages
  package:
    name:
      - build-essentials

# - name: software | remove unneeded workstation packages on debian and ubuntu hosts
#   tags: cleanup,packages,workstation-packages
#   package:
#     state: absent
#     name:
#       - firefox*
#       - libreoffice-base-core
#       - libreoffice-calc
#       - libreoffice-common
#       - libreoffice-core
#       - libreoffice-draw
#       - libreoffice-gnome
#       - libreoffice-gtk3
#       - libreoffice-impress
#       - libreoffice-math
#       - libreoffice-writer
#       - thunderbird*
#   when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]